AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/index
      Runtime: go1.x
      Environment:
        Variables:
          REGIONS: us-east-1,us-east-2,us-west-1,us-west-2
      Policies: AmazonEC2ReadOnlyAccess
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: post
  Version:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/version
      Runtime: go1.x
      Environment:
        Variables:
          REGIONS: us-east-1,us-east-2,us-west-1,us-west-2
      Policies: AmazonEC2ReadOnlyAccess
      Events:
        Version:
          Type: Api
          Properties:
            Path: /version
            Method: get
  Ls:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/ls
      Runtime: go1.x
      Environment:
        Variables:
          REGIONS: us-east-1,us-east-2,us-west-1,us-west-2
      Policies: AmazonEC2ReadOnlyAccess
      Events:
        Tmp:
          Type: Api
          Properties:
            Path: /ls
            Method: get
Outputs:
  RestUrl:
    Description: External Rest Api url
    Value:
      !Join [
        "",
        [
          "https://",
          !Ref ServerlessRestApi,
          ".execute-api.",
          !Ref "AWS::Region",
          ".amazonaws.com/",
          !Ref ServerlessRestApiProdStage,
        ],
      ]
